export const CREATE_SESSION = 'CREATE_SESSION';
export const EDIT_SESSION = 'EDIT_SESSION';
export const EDIT_SESSION_DATA_CHANGED = 'EDIT_SESSION_DATA_CHANGED';
export const LOAD_SESSIONS = 'LOAD_SESSIONS';
export const SAVE_SESSION = 'SAVE_SESSION';
export const VIEW_SESSION_LIST = 'VIEW_SESSION_LIST';
